// react-intro/src/Modal.jsx
// react-intro/src/Modal.jsx

export default function Modal({ open, title, children, onClose, onConfirm }) {
    if (!open) return null;

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal" onClick={(event) => event.stopPropagation()}>
                <div className="modal-mark">ATLAS / NOTE</div>

                <h3>{title}</h3>

                <div className="modal-content">{children}</div>

                <div className="modal-actions">
                    <button
                        type="button"
                        className="modal-cancel"
                        onClick={onClose}
                    >
                        Cancel
                    </button>

                    <button
                        type="button"
                        className="modal-confirm"
                        onClick={onConfirm}
                    >
                        Delete
                    </button>
                </div>
            </div>
        </div>
    );
}

// vue-intro/src/components/Modal.vue
<script setup>
defineProps({
    open: {
        type: Boolean,
        default: false,
    },
    title: {
        type: String,
        default: '',
    },
});

const emit = defineEmits(['close', 'confirm']);

const closeOnBackdrop = (event) => {
    if (event.target === event.currentTarget) {
        emit('close');
    }
};
</script>

<template>
    <div v-if="open" class="modal-backdrop" @click="closeOnBackdrop">
        <div class="modal-dialog" role="dialog">
            <button type="button" class="modal-close" @click="emit('close')">
                ×
            </button>

            <h3>{{ title }}</h3>

            <div class="modal-content">
                <slot />
            </div>

            <div class="modal-actions">
                <button
                    type="button"
                    class="modal-cancel"
                    @click="emit('close')"
                >
                    Cancel
                </button>

                <button
                    type="button"
                    class="modal-confirm"
                    @click="emit('confirm')"
                >
                    Confirm
                </button>
            </div>
        </div>
    </div>
</template>
